### ISSUE TITLE
Typo修正お願いします

### ISSUE THREAD

**Issue by yossy11** [hiyashinsudo/heroku-test#1]
## 概要
検索ワード指定時の返信でメッセージが一部「なだ」となっているので「だな」に変更してください

**Comment by hiyashinsudo** [comment]
issueありがとうございますんご
なんとかPRできましたので、レビューお願いしますんご
https://github.com/hiyashinsudo/heroku-test/pull/2

**Comment by yossy11** [comment]
語尾をなんとかしたまえンゴ

**Comment by hiyashinsudo** [comment]
んご、語尾はなんとかしたいと思ってるッピ
